version: 2

models:
  - name: fact_customer_incremental
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null